name: Scrape AHL Standings

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Ruby gems
        run: gem install capybara selenium-webdriver nokogiri json

      - name: Run scraper
        run: ruby scrape.rb

      - name: Commit results
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add standings.json debug.html
          git diff --cached --quiet || git commit -m "Update standings"
          git push
