name: Scrape Ontario Reign Standings

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Nokogiri
        run: gem install nokogiri

      - name: Run scraper
        run: ruby scrape.rb

      - name: Commit results
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add standings.json debug.json
          git diff --cached --quiet || git commit -m "Update Ontario Reign standings"
          git push
