name: Scrape AHL Standings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scraper
        run: npm run scrape

      - name: Commit updated standings
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add standings.json debug.txt
          git commit -m "Update standings"
          git push
